name: chattor_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.3

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  get_it: ^7.6.4
  flutter_riverpod: ^2.4.9
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  country_picker: ^2.0.23
  image_picker: ^1.0.6
  firebase_app_check: ^0.2.1+8
  flutter_contacts: ^1.1.7+1
  uuid: ^4.3.3
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  video_player: ^2.8.2
  emoji_picker_flutter: ^2.1.0
  enough_giphy_flutter: ^0.4.1
  record: ^5.0.4
  path_provider: ^2.1.2
  audioplayers: ^5.2.1
  swipe_to: ^1.0.5
  agora_uikit: ^1.3.8
  permission_handler: ^11.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/32x32/
    - assets/icons/64x64/
    - assets/icons/128x128/
    - assets/images/
